# .readthedocs.yml

build:
    image: latest

python:
    version: 3.6
    pip_install: true
    use_system_site_packages: true
    extra_requirements: 
        - full
  
requirements_file: docs/requirements.txt

