# .readthedocs.yml

version: 2

formats: all

build:
    image: latest

python:
    version: 3.7
    install:
        - requirements: docs/requirements.txt
        - method: setuptools
    system_packages: false
 

